# Config file for automatic testing at travis-ci.org
language: python
matrix:
  include:
    - python: "2.7"
      env: TEST_TYPE="django18"
    - python: "3.4"
      env: TEST_TYPE="django18"
    - python: "3.5"
      env: TEST_TYPE="django18"
    - python: "3.5"
      env: TEST_TYPE="django19"
    - python: "3.5"
      env: TEST_TYPE="django110"
    - python: "3.5"
      env: TEST_TYPE="django111"
    - python: "3.4"
      env: TEST_TYPE="django20"
    - python: "3.6"
      env: TEST_TYPE="django20"
    - python: "3.6"
      env: TEST_TYPE="django21"
    - python: "2.7"
      env: TEST_TYPE="checkmanifest"
    - python: "2.7"
      env: TEST_TYPE="flake8"
    - python: "2.7"
      env: TEST_TYPE="isort"

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
- pip install tox>=2.1 tox-travis
- pip install coveralls coverage
addons:
  firefox: "latest"
script:
- coverage erase
- tox
after_success:
- coverage combine
- coveralls
sudo: false
