
[tool.black]
line-length = 120
# required-version = '21.12b0' # see https://github.com/psf/black/issues/2493
target-version = ['py39']


[tool.isort]
line_length = 120
profile = "black"
multi_line_output = 3
skip = ["node_modules", ".git", ".tox", "build"]
known_first_party = ["django_functest"]
